server:
  port: 8090
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=example1
    username: postgres
    password: 0688
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: user
      password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.springframework.transaction.interceptor: TRACE

